//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cauhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cauhoi()
        {
            this.chitietdethis = new HashSet<chitietdethi>();
            this.chitietketquas = new HashSet<chitietketqua>();
        }
    
        public int ID { get; set; }
        public string noidung { get; set; }
        public int madokho { get; set; }
        public int mamonhoc { get; set; }
        public int machuong { get; set; }
        public Nullable<int> nguoitao { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        public virtual chuong chuong { get; set; }
        public virtual dokho dokho { get; set; }
        public virtual monhoc monhoc { get; set; }
        public virtual nguoidung nguoidung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdethi> chitietdethis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietketqua> chitietketquas { get; set; }
    }
}
