//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietquyen
    {
        public int ID { get; set; }
        public int manhomquyen { get; set; }
        public int chucnang { get; set; }
        public string hanhdong { get; set; }
    
        public virtual danhmucchucnang danhmucchucnang { get; set; }
        public virtual nhomquyen nhomquyen { get; set; }
    }
}
