//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietthongbao
    {
        public int ID { get; set; }
        public int mathongbao { get; set; }
        public int manhom { get; set; }
    
        public virtual nhom nhom { get; set; }
        public virtual thongbao thongbao { get; set; }
    }
}
