//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitietdethi
    {
        public int ID { get; set; }
        public int macauhoi { get; set; }
        public int made { get; set; }
        public Nullable<int> thutu { get; set; }
    
        public virtual cauhoi cauhoi { get; set; }
        public virtual dethi dethi { get; set; }
    }
}
