//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dethi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dethi()
        {
            this.chitietdethis = new HashSet<chitietdethi>();
            this.dethitudongs = new HashSet<dethitudong>();
            this.giaodethis = new HashSet<giaodethi>();
        }
    
        public int ID { get; set; }
        public int mamon { get; set; }
        public int nguoitao { get; set; }
        public string tende { get; set; }
        public Nullable<System.DateTime> thoigiantao { get; set; }
        public Nullable<int> thoigianthi { get; set; }
        public Nullable<System.DateTime> thoigianbatdau { get; set; }
        public Nullable<System.DateTime> thoigianketthuc { get; set; }
        public Nullable<bool> hienthibailam { get; set; }
        public Nullable<bool> xemdiemthi { get; set; }
        public Nullable<bool> xemdapan { get; set; }
        public Nullable<bool> troncauhoi { get; set; }
        public Nullable<bool> trondapan { get; set; }
        public Nullable<bool> nopbaichuyentab { get; set; }
        public Nullable<int> socaude { get; set; }
        public Nullable<int> socautb { get; set; }
        public Nullable<int> socaukho { get; set; }
        public int trangthai { get; set; }
        public Nullable<int> loaide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietdethi> chitietdethis { get; set; }
        public virtual monhoc monhoc { get; set; }
        public virtual nguoidung nguoidung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dethitudong> dethitudongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giaodethi> giaodethis { get; set; }
    }
}
