//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class giaodethi
    {
        public int ID { get; set; }
        public int manhom { get; set; }
        public int made { get; set; }
        public int maketqua { get; set; }
        public int manguoidung { get; set; }
        public Nullable<float> diemthi { get; set; }
        public Nullable<System.DateTime> thoigianvaothi { get; set; }
        public Nullable<int> thoigianlambai { get; set; }
        public Nullable<int> socaudung { get; set; }
        public Nullable<int> solanchuyentab { get; set; }
    
        public virtual chitietketqua chitietketqua { get; set; }
        public virtual dethi dethi { get; set; }
        public virtual nguoidung nguoidung { get; set; }
        public virtual nhom nhom { get; set; }
    }
}
