//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoidung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoidung()
        {
            this.cauhois = new HashSet<cauhoi>();
            this.dethis = new HashSet<dethi>();
            this.giaodethis = new HashSet<giaodethi>();
            this.chitietnhoms = new HashSet<chitietnhom>();
            this.phancongs = new HashSet<phancong>();
        }
    
        public int ID { get; set; }
        public string email { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string avatar { get; set; }
        public Nullable<System.DateTime> ngaythamgia { get; set; }
        public string matkhau { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string sodienthoai { get; set; }
        public string token { get; set; }
        public string otp { get; set; }
        public Nullable<int> manhomquyen { get; set; }
        public Nullable<int> manguoidung { get; set; }
        public Nullable<System.DateTime> otp_created_at { get; set; }
        public Nullable<System.DateTime> token_expire { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cauhoi> cauhois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dethi> dethis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giaodethi> giaodethis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietnhom> chitietnhoms { get; set; }
        public virtual nhomquyen nhomquyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<phancong> phancongs { get; set; }
    }
}
