//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhom()
        {
            this.chitietthongbaos = new HashSet<chitietthongbao>();
            this.giaodethis = new HashSet<giaodethi>();
            this.chitietnhoms = new HashSet<chitietnhom>();
        }
    
        public int ID { get; set; }
        public string tennhom { get; set; }
        public Nullable<int> mamoi { get; set; }
        public Nullable<int> siso { get; set; }
        public string ghichu { get; set; }
        public string namhoc { get; set; }
        public string hocky { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> hienthi { get; set; }
        public int giangvien { get; set; }
        public int mamonhoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietthongbao> chitietthongbaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giaodethi> giaodethis { get; set; }
        public virtual monhoc monhoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietnhom> chitietnhoms { get; set; }
    }
}
