//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class phancong
    {
        public int ID { get; set; }
        public int mamonhoc { get; set; }
        public int manguoidung { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        public virtual monhoc monhoc { get; set; }
        public virtual nguoidung nguoidung { get; set; }
    }
}
